services:
  bitwarden-backup:
    container_name: bitwarden-backup
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Paths
      - BACKUP_PATH=${BACKUP_PATH:-/backup}
      - BW_BINARY=/usr/local/bin/bw
      # Authentication
      - BW_CLIENT_ID=${BW_CLIENT_ID}
      - BW_CLIENT_SECRET=${BW_CLIENT_SECRET}
      - BW_MASTER_PASSWORD=${BW_MASTER_PASSWORD}
      # Connection
      - BW_SERVER=${BW_SERVER:-https://vault.bitwarden.com}
      # Backups
      - BACKUP_FORMAT=${BACKUP_FORMAT:-encrypted_json}
      - BACKUP_PASSWORD=${BACKUP_PASSWORD}
      - BACKUP_ORGANIZATIONS=${BACKUP_ORGANIZATIONS}
      # Cron
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 1 * * *}
      # NTFY
      - NTFY_SERVER=${NTFY_SERVER:https://ntfy.sh}
      - NTFY_TOPIC=${NTFY_TOPIC}
      - NTFY_USERNAME=${NTFY_USERNAME}
      - NTFY_PASSWORD=${NTFY_PASSWORD}
    volumes:
      - ./backup:/backup
