services:
  bitwarden-backup:
    container_name: bitwarden-backup
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Paths
      - CONFIG_PATH=${CONFIG_PATH:-/config/config.yml}
      - BACKUP_PATH=${BACKUP_PATH:-/backup}
      - BW_BINARY=/usr/local/bin/bw
      # Authentication
      - BW_CLIENT_ID=${BW_CLIENT_ID}
      - BW_CLIENT_SECRET=${BW_CLIENT_SECRET}
      - BW_MASTER_PASSWORD=${BW_MASTER_PASSWORD}
      # Backups
      - BACKUP_FORMAT=${BACKUP_FORMAT:-encrypted_json}
      - BACKUP_PASSWORD=${BACKUP_PASSWORD}
    volumes:
      - ./backup:/backup
      - ./config:/config
